# This is an example config file

# Querator currently supports "badger" and "memory" storage drivers
# TODO: Need to document all options for each storage driver

logging:
  # The logging handler; options are 'color', 'text', 'json'
  handler: text
  # The logging level; options are 'info', 'warn', 'error', 'debug',
  level: info

# Queue Storage defines where metadata about the queues is stored
queue-storage:
  driver: badger
  config:
    storage-dir: /tmp/badger-queue.db

# Partition Storage defines where partitions are stored
partition-storage:
  - name: badger-01
    driver: badger
    affinity: 1
    config:
      storage-dir: /tmp/badger-01.db

#  - name: postgres-01
#    driver: postgres
#    affinity: 1
#
#    config:
#      host: localhost
#      port: 5432
#      user: foo
#      pass: bar
#      database: querator
#      ca-file: /path/to/ca
#      client-cert: /path/to/client/cert
#      client-key: /path/to/client/key

#  - name: mongodb-01
#    driver: mongoDB
#    affinity: 1
#
#    config:
#      host: localhost
#      port: 27017
#      user: foo
#      pass: bar
#      database: querator
#      ca-file: /path/to/ca
#      client-cert: /path/to/client/cert
#      client-key: /path/to/client/key

# Queues is a convenience that allows users to define queues without needing
# to call the /v1/queues.create after querator starts.
queues:
  - name: queue-1
    lease-timeout: 10m
    expire-timeout: 10m
    dead-queue: queue-1-dead
    max-attempts: 10
    reference: test
    requested-partitions: 20
    partitions:
      - partition: 0
        read-only: false
        storage-name: badger-01
#      - partition: 1
#        read-only: false
#        storage-name: postgres-01
#      - partition: 2
#        read-only: false
#        storage-name: mongodb-01
