//
//Copyright 2024 Derrick J Wippler
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        (unknown)
// source: proto/apikeys.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type APIKeyMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,proto3" json:"user_id,omitempty"`
	NamespaceScope string                 `protobuf:"bytes,3,opt,name=namespace_scope,proto3" json:"namespace_scope,omitempty"`
	Name           string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Prefix         string                 `protobuf:"bytes,5,opt,name=prefix,proto3" json:"prefix,omitempty"`
	ExpiresAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,proto3" json:"expires_at,omitempty"`
	LastUsedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_used_at,proto3" json:"last_used_at,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,proto3" json:"created_at,omitempty"`
}

func (x *APIKeyMetadata) Reset() {
	*x = APIKeyMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_apikeys_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIKeyMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIKeyMetadata) ProtoMessage() {}

func (x *APIKeyMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apikeys_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIKeyMetadata.ProtoReflect.Descriptor instead.
func (*APIKeyMetadata) Descriptor() ([]byte, []int) {
	return file_proto_apikeys_proto_rawDescGZIP(), []int{0}
}

func (x *APIKeyMetadata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *APIKeyMetadata) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *APIKeyMetadata) GetNamespaceScope() string {
	if x != nil {
		return x.NamespaceScope
	}
	return ""
}

func (x *APIKeyMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *APIKeyMetadata) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *APIKeyMetadata) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *APIKeyMetadata) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

func (x *APIKeyMetadata) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type APIKeyCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,proto3" json:"user_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	NamespaceScope string                 `protobuf:"bytes,3,opt,name=namespace_scope,proto3" json:"namespace_scope,omitempty"`
	ExpiresAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,proto3" json:"expires_at,omitempty"`
	KeyTag         string                 `protobuf:"bytes,5,opt,name=key_tag,proto3" json:"key_tag,omitempty"`
}

func (x *APIKeyCreateRequest) Reset() {
	*x = APIKeyCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_apikeys_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIKeyCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIKeyCreateRequest) ProtoMessage() {}

func (x *APIKeyCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apikeys_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIKeyCreateRequest.ProtoReflect.Descriptor instead.
func (*APIKeyCreateRequest) Descriptor() ([]byte, []int) {
	return file_proto_apikeys_proto_rawDescGZIP(), []int{1}
}

func (x *APIKeyCreateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *APIKeyCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *APIKeyCreateRequest) GetNamespaceScope() string {
	if x != nil {
		return x.NamespaceScope
	}
	return ""
}

func (x *APIKeyCreateRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *APIKeyCreateRequest) GetKeyTag() string {
	if x != nil {
		return x.KeyTag
	}
	return ""
}

type APIKeyCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Key    string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Prefix string `protobuf:"bytes,3,opt,name=prefix,proto3" json:"prefix,omitempty"`
}

func (x *APIKeyCreateResponse) Reset() {
	*x = APIKeyCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_apikeys_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIKeyCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIKeyCreateResponse) ProtoMessage() {}

func (x *APIKeyCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apikeys_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIKeyCreateResponse.ProtoReflect.Descriptor instead.
func (*APIKeyCreateResponse) Descriptor() ([]byte, []int) {
	return file_proto_apikeys_proto_rawDescGZIP(), []int{2}
}

func (x *APIKeyCreateResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *APIKeyCreateResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *APIKeyCreateResponse) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type APIKeysListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,proto3" json:"user_id,omitempty"`
	Limit  int32  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Pivot  string `protobuf:"bytes,3,opt,name=pivot,proto3" json:"pivot,omitempty"`
}

func (x *APIKeysListRequest) Reset() {
	*x = APIKeysListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_apikeys_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIKeysListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIKeysListRequest) ProtoMessage() {}

func (x *APIKeysListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apikeys_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIKeysListRequest.ProtoReflect.Descriptor instead.
func (*APIKeysListRequest) Descriptor() ([]byte, []int) {
	return file_proto_apikeys_proto_rawDescGZIP(), []int{3}
}

func (x *APIKeysListRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *APIKeysListRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *APIKeysListRequest) GetPivot() string {
	if x != nil {
		return x.Pivot
	}
	return ""
}

type APIKeysListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*APIKeyMetadata `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *APIKeysListResponse) Reset() {
	*x = APIKeysListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_apikeys_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIKeysListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIKeysListResponse) ProtoMessage() {}

func (x *APIKeysListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apikeys_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIKeysListResponse.ProtoReflect.Descriptor instead.
func (*APIKeysListResponse) Descriptor() ([]byte, []int) {
	return file_proto_apikeys_proto_rawDescGZIP(), []int{4}
}

func (x *APIKeysListResponse) GetItems() []*APIKeyMetadata {
	if x != nil {
		return x.Items
	}
	return nil
}

type APIKeysDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *APIKeysDeleteRequest) Reset() {
	*x = APIKeysDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_apikeys_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIKeysDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIKeysDeleteRequest) ProtoMessage() {}

func (x *APIKeysDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apikeys_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIKeysDeleteRequest.ProtoReflect.Descriptor instead.
func (*APIKeysDeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_apikeys_proto_rawDescGZIP(), []int{5}
}

func (x *APIKeysDeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_proto_apikeys_proto protoreflect.FileDescriptor

var file_proto_apikeys_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x6b, 0x65, 0x79, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x71, 0x75, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x1a,
	0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xc8, 0x02, 0x0a, 0x0e, 0x41, 0x50, 0x49, 0x4b, 0x65, 0x79, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x12, 0x28, 0x0a,
	0x0f, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x73, 0x63, 0x6f, 0x70, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x5f, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70,
	0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x65,
	0x66, 0x69, 0x78, 0x12, 0x3a, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x5f, 0x61,
	0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x5f, 0x61, 0x74, 0x12,
	0x3e, 0x0a, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x12,
	0x3a, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x22, 0xc3, 0x01, 0x0a, 0x13,
	0x41, 0x50, 0x49, 0x4b, 0x65, 0x79, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x28, 0x0a, 0x0f, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x73,
	0x63, 0x6f, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x6e, 0x61, 0x6d, 0x65,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x12, 0x3a, 0x0a, 0x0a, 0x65,
	0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x65, 0x78, 0x70,
	0x69, 0x72, 0x65, 0x73, 0x5f, 0x61, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x5f, 0x74,
	0x61, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x5f, 0x74, 0x61,
	0x67, 0x22, 0x50, 0x0a, 0x14, 0x41, 0x50, 0x49, 0x4b, 0x65, 0x79, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x70,
	0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x65,
	0x66, 0x69, 0x78, 0x22, 0x5a, 0x0a, 0x12, 0x41, 0x50, 0x49, 0x4b, 0x65, 0x79, 0x73, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x69, 0x76,
	0x6f, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x69, 0x76, 0x6f, 0x74, 0x22,
	0x45, 0x0a, 0x13, 0x41, 0x50, 0x49, 0x4b, 0x65, 0x79, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x71, 0x75, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72,
	0x2e, 0x41, 0x50, 0x49, 0x4b, 0x65, 0x79, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x26, 0x0a, 0x14, 0x41, 0x50, 0x49, 0x4b, 0x65, 0x79,
	0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x42, 0x26,
	0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x61, 0x70,
	0x65, 0x74, 0x61, 0x6e, 0x2d, 0x69, 0x6f, 0x2f, 0x71, 0x75, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_apikeys_proto_rawDescOnce sync.Once
	file_proto_apikeys_proto_rawDescData = file_proto_apikeys_proto_rawDesc
)

func file_proto_apikeys_proto_rawDescGZIP() []byte {
	file_proto_apikeys_proto_rawDescOnce.Do(func() {
		file_proto_apikeys_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_apikeys_proto_rawDescData)
	})
	return file_proto_apikeys_proto_rawDescData
}

var file_proto_apikeys_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_apikeys_proto_goTypes = []interface{}{
	(*APIKeyMetadata)(nil),        // 0: querator.APIKeyMetadata
	(*APIKeyCreateRequest)(nil),   // 1: querator.APIKeyCreateRequest
	(*APIKeyCreateResponse)(nil),  // 2: querator.APIKeyCreateResponse
	(*APIKeysListRequest)(nil),    // 3: querator.APIKeysListRequest
	(*APIKeysListResponse)(nil),   // 4: querator.APIKeysListResponse
	(*APIKeysDeleteRequest)(nil),  // 5: querator.APIKeysDeleteRequest
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_proto_apikeys_proto_depIdxs = []int32{
	6, // 0: querator.APIKeyMetadata.expires_at:type_name -> google.protobuf.Timestamp
	6, // 1: querator.APIKeyMetadata.last_used_at:type_name -> google.protobuf.Timestamp
	6, // 2: querator.APIKeyMetadata.created_at:type_name -> google.protobuf.Timestamp
	6, // 3: querator.APIKeyCreateRequest.expires_at:type_name -> google.protobuf.Timestamp
	0, // 4: querator.APIKeysListResponse.items:type_name -> querator.APIKeyMetadata
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_apikeys_proto_init() }
func file_proto_apikeys_proto_init() {
	if File_proto_apikeys_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_apikeys_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIKeyMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_apikeys_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIKeyCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_apikeys_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIKeyCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_apikeys_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIKeysListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_apikeys_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIKeysListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_apikeys_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIKeysDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_apikeys_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_apikeys_proto_goTypes,
		DependencyIndexes: file_proto_apikeys_proto_depIdxs,
		MessageInfos:      file_proto_apikeys_proto_msgTypes,
	}.Build()
	File_proto_apikeys_proto = out.File
	file_proto_apikeys_proto_rawDesc = nil
	file_proto_apikeys_proto_goTypes = nil
	file_proto_apikeys_proto_depIdxs = nil
}
